name: Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches:
      - main  # Ajusta según la rama principal de tu repositorio

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Display repository contents
        run: ls -R  # Muestra el contenido del directorio actual para verificar

      - name: Change to project directory
        run: |
          cd path/to/your/project/directory  # Ajusta según la ruta real a tu directorio de proyecto
          dotnet publish -c Release -o output  # Ajusta según la configuración de publicación de tu proyecto

      - name: Rewrite base href
        if: success()
        uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
        with:
          html_path: output/wwwroot/index.html  # Ajusta según la ruta real a tu archivo index.html generado
          base_href: /repository-name  # Ajusta según la URL base donde se alojará la aplicación

      - name: Add .nojekyll file
        run: touch output/wwwroot/.nojekyll

      - name: Commit to GitHub Pages Repo
        if: success()
        uses: crazy-max/ghaction-github-pages@v1.5.1
        with:
          target_branch: gh-pages  # Ajusta según el branch de destino de GitHub Pages
          build_dir: output/wwwroot  # Ajusta según la ruta real al directorio de construcción de tu proyecto
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
